os: linux
dist: xenial

# Tell Travis you want a Python environment to test in
language: python
# List the versions of Python you'd like to test against
services:
  - postgresql
  - mysql
env:
  global:
    - DJANGO_SETTINGS_MODULE=tests.settings
  jobs:
    - DJANGO_VERSION=2.2.* DB=mysql
    - DJANGO_VERSION=2.2.* DB=postgres
    - DJANGO_VERSION=2.2.* DB=sqlite
    - DJANGO_VERSION=3.1.* DB=mysql
    - DJANGO_VERSION=3.1.* DB=postgres
    - DJANGO_VERSION=3.1.* DB=sqlite
    - DJANGO_VERSION=3.2.* DB=mysql
    - DJANGO_VERSION=3.2.* DB=postgres
    - DJANGO_VERSION=3.2.* DB=sqlite
python:
  - "3.6"
  - "3.7"
  - "3.8"
  - "3.9"
# Tell it the things it will need to install when it boots
install:
  - pip install -q pytz coveralls flake8 psycopg2 mysqlclient
  - pip install -q "Django==$DJANGO_VERSION"
  - pip install -e .
# Tell Travis how to run the test script itself
before_script:
  - mysql_tzinfo_to_sql /usr/share/zoneinfo | mysql -u root mysql
script:
  - flake8 naivedatetimefield/
  - coverage run --parallel-mode --source=naivedatetimefield runtests.py
  - coverage combine
# after_success: coveralls
